### ISSUE TITLE
Feature Request: Create Polls triggered by user

### ISSUE THREAD

**Issue by muckelba** [pokepark/PokemonRaidBot#50]
Our Town is scanning and creating polls for raids automatically, but that causes a bit spam and gets a bit messy. A solution would be to only have the raid-overview and add a link or button to create the poll when needed. So only interesting polls exist in the channel/chat.

The raids would be still in the database, but not posted. I'm not sure how complicated it is at the moment to implement that, but i would love to see that kind of option 😄

**Comment by Chefkeks** [comment]
No exactly the same, but currently working on improvements to make raid poll without any participants a lot smaller. So instead of showing all buttons, we just show the time buttons. Next I'll have a look to optimize / reduce the size of the raid poll text as well, e.g. hiding CP values as long as there are no votes. Looking into that currently as it's not possible to create raids afterwards via a link (as far a I can think of). So minimizing the footprint of raid polls without votes would be the best solution I guess.

**Comment by muckelba** [comment]
Good Idea! It could be even more reduced if the "static" buttons like team, level, etc are attached to the raid overview and not to each poll (with attendees). That's obviously only possible in Chats with a raid overview

**Comment by Chefkeks** [comment]
Actually only the row with team, level + and level - makes sense to be splitted away. The other rows (first and last) are specific to each raid poll and therefore should not be taken away, but team/level would be possible.

Regarding the position, I guess we could attach it either to raid overview (if used in a chat) or create a small own message that allows trainers to set their team / level there.

**Comment by muckelba** [comment]
Sounds good! 👍

**Comment by Ninjasoturi** [comment]
I'd say this is not needed since we now have the ability to autoshare polls to a specific chat after the first vote, so you can have a dedicated chat for auto-posting raids from a scanner, and another for raids with participants

**Comment by Artanicus** [comment]
Autosharing on voted polls is already in the main branch so closing this one as fixed.
